# SPDX-License-Identifier: MIT-0

---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      skip_checkout:
        type: boolean
        default: false
      working_directory:
        type: string
        default: .
concurrency:
  # Cancel previous CI runs when additional commits are added to a pull request.
  # This will not cancel CI runs associated with `push`.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  ubuntu_jammy:
    name: ubuntu 22.04 jammy
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    steps:
      - name: ca-certificates
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates
        shell: bash
      - uses: bazelbuild/setup-bazelisk@v2
      - name: checkout
        uses: actions/checkout@v3
        if: ${{ ! inputs.skip_checkout }}
      - name: setup
        run: bazel run //:install_prereqs
        shell: bash
        working-directory: ${{ inputs.working_directory }}
      - name: build and test
        run: bazel test //...
        shell: bash
        working-directory: ${{ inputs.working_directory }}
